version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: defi_guardian_db
    environment:
      POSTGRES_DB: defi_guardian_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d defi_guardian_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres_test:
    image: postgres:15-alpine
    container_name: defi_guardian_test_db
    environment:
      POSTGRES_DB: defi_guardian_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d defi_guardian_test"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
  postgres_test_data: